### ISSUE TITLE
Comment in realtime_box might be wrong and misleading

### ISSUE THREAD

**Issue by firesurfer** [ros-controls/realtime_tools#138]
Hi, as I am currently writing some controllers I started to take a look at the realtime_tools.

The first comment in the realtime_box states:

>   Strongly suggested that you use an std::shared_ptr in this box to guarantee realtime safety.

https://github.com/ros-controls/realtime_tools/blob/441b544ea32afea6658341a50dbadc149a41368a/include/realtime_tools/realtime_box.h#L41

In my opinion one should not use pointers at all with the current implementation of the RealtimeBox as we do:

1. Obtain a lock
2. Copy the stored value to the passed reference
3. Unlock the lock 
4. And now the user will start operating on the pointer

The lock is already released when operations on the actual data are done. 

Perhaps my understanding of the specific case in incomplete (please correct me in that case). 
But I would suggest to actually change the comment in: `Using pointers is not safe with this implementation`

**Comment by bmagyar** [comment]
Agreed. That's just wrong
