### ISSUE TITLE
May I ask you some question？How to use realtime_tools in ros2_control? Is there any example？

### ISSUE THREAD

**Issue by Mark9999999** [ros-controls/realtime_tools#156]

**Comment by saikishor** [comment]
Hello!

A good example could be [`joint_state_broadcaster` ](https://github.com/ros-controls/ros2_controllers/blob/00172ab5dbd4948df78493e5acd40901a7227976/joint_state_broadcaster/src/joint_state_broadcaster.cpp#L154-L160) where the `RealtimePublisher` is being used to publish the `joint_states` .
