### ISSUE TITLE
Allow to rename thread in `RealtimePublisher`

### ISSUE THREAD

**Issue by roncapat** [ros-controls/realtime_tools#176]
At least in Linux, it is possible to rename a thread, via calls like [ptrhead_setname_np](https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html).

For application featuring many `RealtimePublishers` and many other threads, diving into `perf record` outputs (e.g. via `hotspot` tool) is difficult because by default all threads have the same name (First 15 characters of the process name), and thread renaming is a powerful tool to discriminate at a glance which thread does what.

To allow this, either the implementation of `RealtimePublisher` shall permit to obtain the native handle (see [this](https://en.cppreference.com/w/cpp/thread/thread/native_handle)) or may enable for Linux only an additional method that uses `pthread_setname_np`.

I can submit a PR depending on maintainers feedback of course 👍🏻

**Comment by christophfroehlich** [comment]
@saikishor what do you think?

**Comment by roncapat** [comment]
Fine for me, as long as I have a way to access the thread handle :)

**Comment by firesurfer** [comment]
@roncapat I suggest you create a PR for that ;)
