### ISSUE TITLE
why can't be catkin_make ?

### ISSUE THREAD

**Issue by jessieqiqi** [ros-controls/realtime_tools#29]
When i run catkin_make  the latest version,  it failed. The indication on terminal is below .

In file included from /home/hitrobot/catkin_ws/src/control_toolbox/include/control_toolbox/pid.h:49:0,
                 from /home/hitrobot/catkin_ws/src/control_toolbox/src/pid.cpp:41:
/home/hitrobot/catkin_ws/src/realtime_tools-melodic-devel/include/realtime_tools/realtime_publisher.h:232:1: error: expected unqualified-id before ‘using’
 using RealtimePublisherSharedPtr = std::shared_ptr<RealtimePublisher<Msg> >;
 ^
In file included from /home/hitrobot/catkin_ws/src/control_toolbox/include/control_toolbox/pid.h:49:0,
                 from /home/hitrobot/catkin_ws/src/control_toolbox/include/control_toolbox/pid_gains_setter.h:40,
                 from /home/hitrobot/catkin_ws/src/control_toolbox/src/pid_gains_setter.cpp:30:
/home/hitrobot/catkin_ws/src/realtime_tools-melodic-devel/include/realtime_tools/realtime_publisher.h:232:1: error: expected unqualified-id before ‘using’
 using RealtimePublisherSharedPtr = std::shared_ptr<RealtimePublisher<Msg> >;
 ^
make[2]: *** [control_toolbox/CMakeFiles/control_toolbox.dir/src/pid_gains_setter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by bmagyar** [comment]
The github issue tracker is used to track software-related problems. 

Please post your questions to [ROS Answers](https://answers.ros.org/questions/)
