### ISSUE TITLE
real time safe rospy publisher

### ISSUE THREAD

**Issue by bomarali** [ros-controls/realtime_tools#30]
Hi all!

Can anyone explain me the relation between rt kernel and real-time tools. Say I am publishing joint trajectories with a rospy publisher with rt kernel. Is it still unsafe and I should use realtime_tools cpp publisher instead?

**Comment by bmagyar** [comment]
The github issue tracker is used to track software-related problems. 

Please post your questions to [ROS Answers](https://answers.ros.org/questions/)
