### ISSUE TITLE
Porting to ROS 2 Dashing

### ISSUE THREAD

**Issue by sloretz** [ros-controls/realtime_tools#35]
I'm looking into how much work it would be to port this package into ROS 2 Dashing. Mind answering a few questions?

* Is someone already working on this?
* Where should a ros2 port live? How about a `dashing-devel` branch in this repo?
* Would the maintainers be willing to release into Dashing once code has been ported?
* Should the port also eliminate the use of boost? https://github.com/ros-controls/realtime_tools/pull/31#issuecomment-452314598
* Is a partial port OK?
  * For example, I would like to use `RealtimePublisher`, but I don't currently need `RealtimeServerGoalHandle`. Would porting these classes one at a time be acceptable?
* Should the existing code style be maintained, or should the [ROS 2 style guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#id1) be used?

**Comment by bmagyar** [comment]
Hi @sloretz , 
Great list, allow me to answer in the same fashion.

* Not that I know of.
* Works perfectly fine.
* No problem.
* As much as possible, I've been trying to get rid of most boost in favour of standard library.
* I think a partial port may be misleading and harder to maintain. This repo doesn't have that much code TBH. It may be a bigger issue elsewhere.
* Feel free to restyle things, but please try doing it in a separate PR from functional ones. I have only one problem with the style guide: I find `CamelCase` for functions terrible, also most of our existing API uses `camelCase` which is just way more readable and avoids confusing functions with classes.

Hope this helps!

**Comment by ipa-mdl** [comment]
> I find CamelCase for functions terrible, also most of our existing API uses camelCase which is just way more readable and avoids confusing functions with classes.

Urgs, I did not see this before. :+1:  for `camelCase`.

**Comment by sloretz** [comment]
@bmagyar now that #41 is merged :tada:, would you be willing to release realtime_tools into dashing?

**Comment by bmagyar** [comment]
Sorry for the slight delay, here you go: https://github.com/ros/rosdistro/pull/22203
