### ISSUE TITLE
Redeclaration errors of Boost typedefs when compiling ros_controllers

### ISSUE THREAD

**Issue by joaocandre** [ros-controls/realtime_tools#47]
I'm currently getting the following compilation errors when compiling `ros_controllers` from source:

    In file included from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.h:65,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:34:
    /opt/ros/melodic/include/realtime_tools/realtime_server_goal_handle.h:50:37: error: redeclaration of ‘typedef class boost::shared_ptr<typename ActionSpec::_action_result_type::_result_type> realtime_tools::RealtimeServerGoalHandle<Action>::ResultPtr’
       50 |   typedef boost::shared_ptr<Result> ResultPtr;
          |                                     ^~~~~~~~~
    In file included from /opt/ros/melodic/include/actionlib/server/action_server.h:49,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.h:57,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:34:
    /opt/ros/melodic/include/actionlib/action_definition.h:58:37: note: previous declaration ‘typedef class boost::shared_ptr<typename ActionSpec::_action_result_type::_result_type> realtime_tools::RealtimeServerGoalHandle<Action>::ResultPtr’
       58 |   typedef boost::shared_ptr<Result> ResultPtr; \
          |                                     ^~~~~~~~~
    /opt/ros/melodic/include/actionlib/action_definition.h:58:37: note: in definition of macro ‘ACTION_DEFINITION’
       58 |   typedef boost::shared_ptr<Result> ResultPtr; \
          |                                     ^~~~~~~~~
    In file included from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.h:65,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:34:
    /opt/ros/melodic/include/realtime_tools/realtime_server_goal_handle.h:51:39: error: redeclaration of ‘typedef class boost::shared_ptr<typename ActionSpec::_action_feedback_type::_feedback_type> realtime_tools::RealtimeServerGoalHandle<Action>::FeedbackPtr’
       51 |   typedef boost::shared_ptr<Feedback> FeedbackPtr;
          |                                       ^~~~~~~~~~~
    In file included from /opt/ros/melodic/include/actionlib/server/action_server.h:49,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.h:57,
                     from /home/user/ros_ws/src/ros_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:34:
    /opt/ros/melodic/include/actionlib/action_definition.h:63:39: note: previous declaration ‘typedef class boost::shared_ptr<typename ActionSpec::_action_feedback_type::_feedback_type> realtime_tools::RealtimeServerGoalHandle<Action>::FeedbackPtr’
       63 |   typedef boost::shared_ptr<Feedback> FeedbackPtr;
          |                                       ^~~~~~~~~~~
    /opt/ros/melodic/include/actionlib/action_definition.h:63:39: note: in definition of macro ‘ACTION_DEFINITION’
       63 |   typedef boost::shared_ptr<Feedback> FeedbackPtr;
          |                                       ^~~~~~~~~~~

Somehow the code in the `realtime-tools` package is conflicting with the typedefs in `actionlib` package?

**Comment by bmagyar** [comment]
Don't worry, nothing is broken.
Please ensure to pick the right branches when working from source.
