### ISSUE TITLE
Eloquent Bloom Release

### ISSUE THREAD

**Issue by IanTheEngineer** [ros-controls/realtime_tools#48]
I've been using this repo building from source in Eloquent. All seems good (for my use-case at least). Could we release the same version of `realtime_tools` in Eloquent that is [released into dashing](https://github.com/ros/rosdistro/pull/22203)? Thanks!

**Comment by bmagyar** [comment]
Thanks for testing it ;) 
https://github.com/ros/rosdistro/pull/23471
