### ISSUE TITLE
Release realtime_tools to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-controls/realtime_tools#54]
Would you mind releasing `realtime_tools` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 110 repos need it.

I'm not sure how much work it will need. At a minimum it needs #53.

**Comment by bmagyar** [comment]
Added #52 too

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/24037
