### ISSUE TITLE
`realtime_server_goal_handle_tests.cpp` test uses obsolete `fibonacci` action

### ISSUE THREAD

**Issue by zultron** [ros-controls/realtime_tools#65]
On 2019-08-28, commit c596da9a added a reference to the `test_msgs` package `fibonacci` action, now tagged in `2.0.0` in the `foxy-devel` branch.

A few months earlier, the `fibonacci` action was *removed* from `test_msgs` in PR ros2/rcl_interfaces#77, tagged in `0.7.2`; the current `ros-foxy-test-msgs` package version is `1.0.0-1focal.20201007.204652`.

This might not have been caught yet because of a strange packaging issue, where the `fibonacci` action is still included in the `1.0.0` package; see ros2/rcl_interfaces#114.

At any rate, the `fibonacci` action has been removed in dependency packages, and should be removed here, too.

**Comment by christophfroehlich** [comment]
It seems that this is intentionally, and also used by rclcpp and nav2 in this way, see https://github.com/ros2/rcl_interfaces/issues/114
