### ISSUE TITLE
New noetic release including #58

### ISSUE THREAD

**Issue by timonegk** [ros-controls/realtime_tools#70]
The current release for noetic does not build because #58 is not included.

**Comment by bmagyar** [comment]
Every time you report a build failure, please do the courtesy of reporting the setup you encountered this issue in.

The ROS buildfarm was happy with the release the last time I pushed it. I can however push a new release to Noetic if that's what you are trying to ask for in an indirect way? ;)

**Comment by timonegk** [comment]
I'm sorry, I thought it might have been a known problem, hence #58. I am building on Debian Testing where the patch seems to be required.
And yes, I am asking for a new release to noetic :see_no_evil:

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/27994

**Comment by bmagyar** [comment]
have a great day ;)

**Comment by timonegk** [comment]
Thanks a lot, you too :) Everything builds now.

**Comment by bmagyar** [comment]
no worries, thanks for reporting!
