### ISSUE TITLE
Release for Rolling

### ISSUE THREAD

**Issue by henningkayser** [ros-controls/realtime_tools#75]
What's the status on releasing `realtime-tools` for Rolling?
We are planning to [release MoveIt](https://github.com/ros-planning/moveit2/issues/476) targeting Rolling end of June and it would be great if this dependency would be available by then.

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/29666

**Comment by henningkayser** [comment]
Sweet, thanks!
