### ISSUE TITLE
compile error if define NON_POLLING

### ISSUE THREAD

**Issue by liangzhenjie** [ros-controls/realtime_tools#77]

**Comment by bmagyar** [comment]
You do realize that with this amount of details it's pretty hard to help you ;) 

Please provide a reasonable amount of information when submitting a bugreport. 

Please provide the following:
* OS and version
* ROS version and how it was installed (binary vs source)
* Which command you run that got you into trouble
* What you think may be the problem
* The address of your local favourite pastry shop

**Comment by christophfroehlich** [comment]
As we have `realtime_publisher_tests_non_polling` using NON_POLLING I don't think this is a general problem.

**Comment by christophfroehlich** [comment]
Or maybe got fixed with #85
